version: '3'
services:
  dev-api:
    container_name: dev-api
    image: zelejs/allin-web:jdk11
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api:/webapps
      - ./api/lib:/webapps/lib
    environment:
      TZ: "Asia/Shanghai"
    privileged: true

  issue-js:
    image: node:latest
    container_name: issue-js
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./issue/check:/issue
      # YAML本地路径映射
      - ./issue/yaml:/var/yaml
      # swagger文件本地路径映射
      - ./issue/swagger:/var/swagger/
      # crudless工具本地路径映射
      - ./issue/crudless:/var/crudless
      # issue镜像执行脚本
      - ./issue/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      # MySQL信息用于Node.js中Issue检查接口生成检查记录并插入至数据库
      MYSQL_DB: cinema
      MYSQL_HOST: 192.168.3.236
      MYSQL_PORT: 3307
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    entrypoint: ["bash", "/usr/local/bin/entrypoint.sh"]

  db-service:
    image: python:latest
    container_name: db-service
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db-service:/db-service
      # db-service镜像执行脚本（检查处理依赖问题）
      - ./db-service/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      MYSQL_HOST: 192.168.3.236
      MYSQL_PORT: 3307
      MYSQL_DATABASE: cinema
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SAVE_PATH: /db-service
      SAVE_NAME: db.xlsx
    entrypoint: ["bash", "/usr/local/bin/entrypoint.sh"]

networks:
  default:
    external:
      name: ${network}   ## host docker network 